### ISSUE TITLE
lps28.py error in _INTERRUPT_CFG

### ISSUE THREAD

**Issue by mikeabuilder** [jposada202020/CircuitPython_LPS28#1]
I think that the constant _INTERRUPT_CFG  has a typo in in its assignment statement. It says:

`_INTERRUPT_CFG = const(0xB0)`

But the LPS28dfw.pdf (Attached) doc from STMicro says the address should be 0B in the register table map. Possibly it's a documentation error in the pdf. 

[lps28dfw.pdf](https://github.com/user-attachments/files/17807328/lps28dfw.pdf)

**Comment by jposada202020** [comment]
You are right thanks for the feedback :). Solved in the new Release
